# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pulumi.codegen import mapper_pb2 as pulumi_dot_codegen_dot_mapper__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pulumi/codegen/mapper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MapperStub(object):
    """Mapper is a service for getting mappings from other ecosystems to Pulumi.
    This is currently unstable and experimental.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMapping = channel.unary_unary(
                '/codegen.Mapper/GetMapping',
                request_serializer=pulumi_dot_codegen_dot_mapper__pb2.GetMappingRequest.SerializeToString,
                response_deserializer=pulumi_dot_codegen_dot_mapper__pb2.GetMappingResponse.FromString,
                _registered_method=True)


class MapperServicer(object):
    """Mapper is a service for getting mappings from other ecosystems to Pulumi.
    This is currently unstable and experimental.
    """

    def GetMapping(self, request, context):
        """GetMapping tries to find a mapping for the given provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMapping,
                    request_deserializer=pulumi_dot_codegen_dot_mapper__pb2.GetMappingRequest.FromString,
                    response_serializer=pulumi_dot_codegen_dot_mapper__pb2.GetMappingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codegen.Mapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codegen.Mapper', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mapper(object):
    """Mapper is a service for getting mappings from other ecosystems to Pulumi.
    This is currently unstable and experimental.
    """

    @staticmethod
    def GetMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codegen.Mapper/GetMapping',
            pulumi_dot_codegen_dot_mapper__pb2.GetMappingRequest.SerializeToString,
            pulumi_dot_codegen_dot_mapper__pb2.GetMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
